apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-number-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: random-number
  template:
    metadata:
      labels:
        app: random-number
    spec:
      containers:
      - name: random-number-app
        image: <account>.dkr.ecr.us-east-2.amazonaws.com/random-number-app:v1
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/log/app
          name: app-logs
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      - name: filebeat-sidecar
        image: docker.elastic.co/elastic/filebeat:7.17.27
        args: ["-e", "-strict.perms=false"]
        env:
        - name: ELASTICSEARCH_HOST
          value: "http://elasticsearch:9200"
        volumeMounts:
        - name: app-logs
          mountPath: /var/log/app
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
      volumes:
      - name: app-logs
        emptyDir: {}  # Volume compartilhado entre o app e o Filebeat
      - name: filebeat-config
        configMap:
          name: filebeat-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.27
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: single-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.27
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
  type: LoadBalancer
