name: Deploy to AWS ECR with Git Version

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Runs on version tags like v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Get Git version info
        run: |
          echo "GIT_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
          echo "SHORT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$GIT_VERSION .
          docker tag ${{ secrets.ECR_REPOSITORY }}:$GIT_VERSION ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$GIT_VERSION
          docker tag ${{ secrets.ECR_REPOSITORY }}:$GIT_VERSION ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$GIT_VERSION
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
